name: OWASP ZAP Full Scan

on:
    schedule:
        - cron: "0 2 * * 0" # Weekly on Sunday
    workflow_dispatch:

jobs:
    zap-full-scan:
        name: ZAP Full Security Scan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"

            - name: Build and package
              run: mvn clean package -DskipTests

            - name: Build Docker image
              run: docker build -t cicd-demo:test .

            - name: Run application
              run: |
                  docker run -d -p 5000:5000 --name cicd-demo-app cicd-demo:test
                  timeout 60 bash -c 'until curl -f http://localhost:5000/; do sleep 2; done'

            - name: Run ZAP Full Scan
              uses: zaproxy/action-full-scan@v0.10.0
              with:
                  target: "http://localhost:5000"
                  rules_file_name: ".zap/rules.tsv"
                  cmd_options: "-a -j"

            - name: Upload ZAP Report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: zap-report
                  path: report_html.html

            - name: Cleanup
              if: always()
              run: docker stop cicd-demo-app && docker rm cicd-demo-app
